### ISSUE TITLE
Error when walking AAF: Walking <class 'aaf2.components.OperationGroup'> not implemented

### ISSUE THREAD

**Issue by conorhodder** [markreidvfx/pyaaf2#56]
NotImplementedError on aaf2.components.OperationGroup on an AAF exported from Avid MediaComposer 2018.11

Call is technically coming from OpenTimelineIO, however it appears that the error is being generated by the AAF2 module.

`Traceback (most recent call last):
  File "~/read_aaf.py", line 18, in <module>
    main(aaf)
  File "~/read_aaf.py", line 11, in main
    timeline = otio.adapters.read_from_file(aaf_file)
  File "~\lib\site-packages\opentimelineio\adapters\__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "~\lib\site-packages\opentimelineio\adapters\adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "~\lib\site-packages\opentimelineio\plugins\python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 919, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 229, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 236, in _transcribe
    track = _transcribe(slot, item, editRate, masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 339, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 328, in _transcribe
    child = _transcribe(component, item, editRate, masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 333, in _transcribe
    item, metadata, editRate, masterMobs
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 676, in _transcribe_operation_group
    child = _transcribe(segment, item, editRate, masterMobs)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 328, in _transcribe
    child = _transcribe(component, item, editRate, masterMobs)
  File "~\venv\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 249, in _transcribe
    mobs = _find_timecode_mobs(item)
  File "~\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 112, in _find_timecode_mobs
    for c in item.walk():
  File "~\lib\site-packages\aaf2\components.py", line 207, in walk
    type(segment)))
NotImplementedError: Walking <class 'aaf2.components.OperationGroup'> not implemented`

**Comment by conor-hodder** [comment]
Appears to be addressed in PR #35 - will this be merged into pyaaf2 shortly?
