### ISSUE TITLE
Error when opening aaf file

### ISSUE THREAD

**Issue by talosh** [markreidvfx/pyaaf2#97]
Hi guys, having this error when parsing AAF:

Traceback (most recent call last):
  File "aaf_test.py", line 9, in <module>
    with aaf2.open(sys.argv[1], 'r') as f:
  File "/Volumes/dl-tests/lucid/bl-pulls/aaf_test/pyaaf2/aaf2/file.py", line 200, in __init__
    self.metadict.read_properties()
  File "/Volumes/dl-tests/lucid/bl-pulls/aaf_test/pyaaf2/aaf2/metadict.py", line 470, in read_properties
    self.typedefs_by_name[typedef.type_name] = typedef
AttributeError: 'AAFObject' object has no attribute 'type_name'

including the code lines 470 and 471 in "try: except:" block seem to bring a quick fix but might be worth investigating.

The aaf in question attached, it is made with the recent Avid 2021.9 and comes back just fine:
[TestMarkers.aaf.zip](https://github.com/markreidvfx/pyaaf2/files/7304244/TestMarkers.aaf.zip)

Thank you!

**Comment by markreidvfx** [comment]
Looks like a new Type Definition got added ,something called a TypeDefinitionGenericCharacter. First time I've seen that, looks like it was added the SDK in 2018 on that avid2018 branch. I'll add it when I get a chance. Thanks for reporting!

**Comment by markreidvfx** [comment]
The updated data model is now in the [dev](https://github.com/markreidvfx/pyaaf2/tree/dev) branch, this should fix this issue.
